packages:
  - templates/*

patchedDependencies:
  eslint-plugin-no-relative-import-paths@1.6.1: patches/eslint-plugin-no-relative-import-paths@1.6.1.patch
  eslint-plugin-i18next@6.1.3: patches/eslint-plugin-i18next@6.1.3.patch
