/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as KitchenSinkIndexRouteImport } from './routes/kitchen-sink/index'

const IndexLazyRouteImport = createFileRoute('/')()
const ReactQueryIndexLazyRouteImport = createFileRoute('/react-query/')()
const ReactHookFormZodIndexLazyRouteImport = createFileRoute(
  '/react-hook-form-zod/',
)()
const ReactQueryIdIndexLazyRouteImport = createFileRoute('/react-query/$id/')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ReactQueryIndexLazyRoute = ReactQueryIndexLazyRouteImport.update({
  id: '/react-query/',
  path: '/react-query/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/react-query/index.lazy').then((d) => d.Route),
)
const ReactHookFormZodIndexLazyRoute =
  ReactHookFormZodIndexLazyRouteImport.update({
    id: '/react-hook-form-zod/',
    path: '/react-hook-form-zod/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/react-hook-form-zod/index.lazy').then((d) => d.Route),
  )
const KitchenSinkIndexRoute = KitchenSinkIndexRouteImport.update({
  id: '/kitchen-sink/',
  path: '/kitchen-sink/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactQueryIdIndexLazyRoute = ReactQueryIdIndexLazyRouteImport.update({
  id: '/react-query/$id/',
  path: '/react-query/$id/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/react-query/$id/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/kitchen-sink/': typeof KitchenSinkIndexRoute
  '/react-hook-form-zod/': typeof ReactHookFormZodIndexLazyRoute
  '/react-query/': typeof ReactQueryIndexLazyRoute
  '/react-query/$id/': typeof ReactQueryIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/kitchen-sink': typeof KitchenSinkIndexRoute
  '/react-hook-form-zod': typeof ReactHookFormZodIndexLazyRoute
  '/react-query': typeof ReactQueryIndexLazyRoute
  '/react-query/$id': typeof ReactQueryIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/kitchen-sink/': typeof KitchenSinkIndexRoute
  '/react-hook-form-zod/': typeof ReactHookFormZodIndexLazyRoute
  '/react-query/': typeof ReactQueryIndexLazyRoute
  '/react-query/$id/': typeof ReactQueryIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kitchen-sink/'
    | '/react-hook-form-zod/'
    | '/react-query/'
    | '/react-query/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kitchen-sink'
    | '/react-hook-form-zod'
    | '/react-query'
    | '/react-query/$id'
  id:
    | '__root__'
    | '/'
    | '/kitchen-sink/'
    | '/react-hook-form-zod/'
    | '/react-query/'
    | '/react-query/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  KitchenSinkIndexRoute: typeof KitchenSinkIndexRoute
  ReactHookFormZodIndexLazyRoute: typeof ReactHookFormZodIndexLazyRoute
  ReactQueryIndexLazyRoute: typeof ReactQueryIndexLazyRoute
  ReactQueryIdIndexLazyRoute: typeof ReactQueryIdIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-query/': {
      id: '/react-query/'
      path: '/react-query'
      fullPath: '/react-query/'
      preLoaderRoute: typeof ReactQueryIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-hook-form-zod/': {
      id: '/react-hook-form-zod/'
      path: '/react-hook-form-zod'
      fullPath: '/react-hook-form-zod/'
      preLoaderRoute: typeof ReactHookFormZodIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-sink/': {
      id: '/kitchen-sink/'
      path: '/kitchen-sink'
      fullPath: '/kitchen-sink/'
      preLoaderRoute: typeof KitchenSinkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-query/$id/': {
      id: '/react-query/$id/'
      path: '/react-query/$id'
      fullPath: '/react-query/$id/'
      preLoaderRoute: typeof ReactQueryIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  KitchenSinkIndexRoute: KitchenSinkIndexRoute,
  ReactHookFormZodIndexLazyRoute: ReactHookFormZodIndexLazyRoute,
  ReactQueryIndexLazyRoute: ReactQueryIndexLazyRoute,
  ReactQueryIdIndexLazyRoute: ReactQueryIdIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
