/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReactQueryIndexRouteImport } from './routes/react-query/index'
import { Route as ReactHookFormZodIndexRouteImport } from './routes/react-hook-form-zod/index'
import { Route as KitchenSinkIndexRouteImport } from './routes/kitchen-sink/index'
import { Route as ReactQueryIdIndexRouteImport } from './routes/react-query/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactQueryIndexRoute = ReactQueryIndexRouteImport.update({
  id: '/react-query/',
  path: '/react-query/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactHookFormZodIndexRoute = ReactHookFormZodIndexRouteImport.update({
  id: '/react-hook-form-zod/',
  path: '/react-hook-form-zod/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenSinkIndexRoute = KitchenSinkIndexRouteImport.update({
  id: '/kitchen-sink/',
  path: '/kitchen-sink/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactQueryIdIndexRoute = ReactQueryIdIndexRouteImport.update({
  id: '/react-query/$id/',
  path: '/react-query/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kitchen-sink/': typeof KitchenSinkIndexRoute
  '/react-hook-form-zod/': typeof ReactHookFormZodIndexRoute
  '/react-query/': typeof ReactQueryIndexRoute
  '/react-query/$id/': typeof ReactQueryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kitchen-sink': typeof KitchenSinkIndexRoute
  '/react-hook-form-zod': typeof ReactHookFormZodIndexRoute
  '/react-query': typeof ReactQueryIndexRoute
  '/react-query/$id': typeof ReactQueryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kitchen-sink/': typeof KitchenSinkIndexRoute
  '/react-hook-form-zod/': typeof ReactHookFormZodIndexRoute
  '/react-query/': typeof ReactQueryIndexRoute
  '/react-query/$id/': typeof ReactQueryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kitchen-sink/'
    | '/react-hook-form-zod/'
    | '/react-query/'
    | '/react-query/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kitchen-sink'
    | '/react-hook-form-zod'
    | '/react-query'
    | '/react-query/$id'
  id:
    | '__root__'
    | '/'
    | '/kitchen-sink/'
    | '/react-hook-form-zod/'
    | '/react-query/'
    | '/react-query/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KitchenSinkIndexRoute: typeof KitchenSinkIndexRoute
  ReactHookFormZodIndexRoute: typeof ReactHookFormZodIndexRoute
  ReactQueryIndexRoute: typeof ReactQueryIndexRoute
  ReactQueryIdIndexRoute: typeof ReactQueryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-query/': {
      id: '/react-query/'
      path: '/react-query'
      fullPath: '/react-query/'
      preLoaderRoute: typeof ReactQueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-hook-form-zod/': {
      id: '/react-hook-form-zod/'
      path: '/react-hook-form-zod'
      fullPath: '/react-hook-form-zod/'
      preLoaderRoute: typeof ReactHookFormZodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-sink/': {
      id: '/kitchen-sink/'
      path: '/kitchen-sink'
      fullPath: '/kitchen-sink/'
      preLoaderRoute: typeof KitchenSinkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-query/$id/': {
      id: '/react-query/$id/'
      path: '/react-query/$id'
      fullPath: '/react-query/$id/'
      preLoaderRoute: typeof ReactQueryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KitchenSinkIndexRoute: KitchenSinkIndexRoute,
  ReactHookFormZodIndexRoute: ReactHookFormZodIndexRoute,
  ReactQueryIndexRoute: ReactQueryIndexRoute,
  ReactQueryIdIndexRoute: ReactQueryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
