name: Setup Node Environment
description: Setup node environment for monorepo workflows

runs:
  using: 'composite'
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v6
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
