name: Application Type Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  application-types:
    runs-on: ubuntu-latest
    name: Application Type Checks
    steps:
      - name: Checkout latest
        uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node-environment
      - name: Check application types
        run: >-
          pnpm exec turbo check-types
          --filter=next-ssr
          --filter=react-router-spa
          --filter=react-router-ssr
          --filter=tanstack-router-spa
          --filter=tanstack-start-ssr
          --concurrency=1
        env:
          VITE_APP_ENVIRONMENT: dev
          VITE_APP_MSW_ENABLED: false
          NEXT_PUBLIC_APP_ENVIRONMENT: dev
